#pragma once
#include <map>
#include <vector>
#include "Bitmap.h"
#include "BitmapManager.h"
enum class PLAYER
{
	PLAYER_BLACK = 0,
	PLAYER_WHITE ,
	PLAYER_NON,
	PLAYER_COUNT
};
enum class CHESS_INDEX
{
	CHESS_INDEX_START,
	INDEX_BLACK_PAWN=0,
	INDEX_BLACK_KNIGHT,
	INDEX_BLACK_BISHOP,
	INDEX_BLACK_ROOK,
	INDEX_BLACK_QUEEN,
	INDEX_BLACK_KING,
	INDEX_WHITE_PAWN,
	INDEX_WHITE_KNIGHT,
	INDEX_WHITE_BISHOP,
	INDEX_WHITE_ROOK,
	INDEX_WHITE_QUEEN,
	INDEX_WHITE_KING,
	INDEX_TILE1,
	INDEX_TILE2,
	INDEX_TILE3,
	INDEX_MOVEABLETILE,
	INDEX_BG_0,
	INDEX_BG_1,
	INDEX_BG_2,
	INDEX_BG_3,
	INDEX_BG_4,
	INDEX_EMPTY,
	INDEX_WHITE_BTN,
	INDEX_BLACK_BTN,
	INDEX_ME,
	INDEX_ENEMY,
	INDEX_READY,
	INDEX_READY_END,
	INDEX_COUNT,
};
enum class MAP_SIZE
{
	SIZE_X = 8,
	SIZE_Y = 8,
};
struct Position
{
	int Pos_X;
	int Pos_Y;
};